# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.0  # Use the latest version of clang-format (or specify a version)
    hooks:
      - id: clang-format
        name: clang-format
        # Limit the hook to only apply to files in specific directories
        files: ^(src/|include/|test/).*\. (cpp|h|c|hpp)$  # Match files only in the src/ and include/ directories
        language_version: system  # Use the system-installed version of clang-format
