#!/bin/bash
# Script to build and test the project, not to be considered as a part of the project itself

# "defensive Programming"
cd "$(dirname "$0")"

# Function to perform the build
build() {
    echo "Building..."   
    mkdir -p build 
    cd build
    cmake ..
    make
    cd ..
}

# usage
usage() {
    echo "Usage: $0 {build|clean|test}"
}

#remove build repo
clean(){
    echo "Cleaning build..."
    rm -r build 
}
# Function to perform the tests
test() {
    build
    echo "Running tests..."
    cd build
    ctest --output-on-failure
    cd ..
}

# Main script execution
case $1 in
  build)
    build
    ;;
  clean)
    clean
    ;;
  test)
    build
    test
    ;;
  *)
    asciiquarium
    usage
    ;;
esac        
