name: CI

on:
  push:
    branches:
      - main
      - 7-setup-dev-env
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y cmake libgtest-dev libeigen3-dev

      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp # Explicitly specifying C++ only

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Build project manually (for C++)
        if: ${{ failure() }} # Only runs if autobuild fails
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
